alpha: 0.01
clip:
epochs: 500
lr: 0.01
lr_decay: step
lr_factor: 0.1
lr_schedule:
  - 300
lr_throttle: True
optimizer: adam
save_period: -1
test_batch_size: 10
test_mode: default
train_batch_size: 10
train_mode: progressive
val_period: 20
warmup_period: 10