defaults:
  - problem: mazes
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ./outputs/${name}/testing-${run_id}
  job_logging:
    handlers:
      file:
        filename: testing.log

name: testing_default

problem:
  model:
    test_iterations:
      low: 0
      high: 10
    model_path: ../../training_default/training-estrous-Joseh

quick_test: True
plot: True